ROOT_DEFINITIONS = [
    ("MOTION", "Physical movement through space"),
    ("TRANSFER", "Transfer of possession or control"),
    ("COMMUNICATION", "Information exchange"),
    ("COGNITION", "Mental processes and thinking"),
    ("PERCEPTION", "Sensory experience"),
    ("CREATION", "Bringing something into existence"),
    ("DESTRUCTION", "Destroying or damaging"),
    ("CHANGE", "Change of state or transformation"),
    ("POSSESSION", "Ownership or having"),
    ("INTENTION", "Purposeful planning and aiming"),
    ("EXISTENCE", "Existence, being, occurrence"),
    ("EMOTION", "Emotional states and feelings"),
    ("DESIRE", "Wanting, wishing, hoping"),
    ("PREFERENCE", "Liking, preferring, favoring"),
    ("JOY", "Happiness, celebration, delight"),
    ("SADNESS", "Grief, sorrow, unhappiness"),
    ("ANGER", "Anger, rage, frustration"),
    ("FEAR", "Fear, anxiety, worry"),
    ("EVALUATION", "Assessing, rating, judging quality"),
    ("COMPARISON", "Comparing, contrasting, distinguishing"),
    ("JUDGMENT", "Formal judgment, condemnation, acquittal"),
    ("APPROVAL", "Approving, endorsing, supporting"),
    ("CRITICISM", "Criticizing, blaming, finding fault"),
    ("SOCIAL", "Social interaction and mingling"),
    ("COOPERATION", "Collaboration and coordination"),
    ("CONFLICT", "Disagreement, fighting, dispute"),
    ("AGREEMENT", "Agreeing, consenting, concurring"),
    ("PROMISE", "Promising, vowing, pledging"),
    ("THREAT", "Threatening, intimidating, menacing"),
    ("REQUEST", "Requesting, asking, begging"),
    ("CAUSATION", "Causing, inducing, triggering"),
    ("PREVENTION", "Preventing, avoiding, prohibiting"),
    ("ENABLEMENT", "Enabling, allowing, permitting"),
    ("ATTEMPT", "Trying, attempting, endeavoring"),
    ("SUCCESS", "Succeeding, achieving, accomplishing"),
    ("FAILURE", "Failing, losing, missing"),
    ("ANALYSIS", "Analyzing, examining, studying"),
    ("MEMORY", "Remembering, recalling, reminding"),
    ("LEARNING", "Learning, studying, practicing"),
    ("TEACHING", "Teaching, instructing, training"),
    ("DECISION", "Deciding, resolving, determining"),
    ("BELIEF", "Believing, trusting, accepting"),
    ("STATE", "State, condition, remaining"),
    ("PROPERTY", "Having properties, seeming, appearing"),
    ("QUANTITY", "Measuring, counting, totaling"),
    ("TIME_RELATION", "Temporal relations: beginning, ending"),
    ("LOCATION_STATE", "Spatial occupation, containment"),
    ("EXPERIENCE", "Experiencing, undergoing, enduring"),
    ("ASSISTANCE", "Helping, aiding, supporting"),
    ("TRAVEL", "Traveling, journeying, touring"),
    ("CAUSE_EFFECT", "Causal relations and results"),
    ("ACTION", "General action, doing, performing"),
    ("CONSUMPTION", "Consuming, eating, drinking"),
    ("REFUSAL", "Refusing, rejecting, declining"),
]

ROLE_DEFINITIONS = [
    ("AGENT", "Volitional initiator of an action", None),
    ("PATIENT", "Entity undergoing a direct change", None),
    ("THEME", "Entity moved, located, or described", None),
    ("GOAL", "Destination, target, or recipient", None),
    ("SOURCE", "Origin, starting point, or giver", None),
    ("INSTRUMENT", "Means or tool used", None),
    ("LOCATION", "Spatial location", None),
    ("TIME", "Temporal location", None),
    ("EXPERIENCER", "Entity experiencing a mental or emotional state", None),
    ("STIMULUS", "Thing that triggers a mental or emotional response", None),
    ("STANDARD", "Reference point for comparison or evaluation", None),
    ("VERDICT", "Outcome of a judgment or evaluation", None),
    ("RESULT", "Result or consequence of causation", None),
    ("PATH", "Route or trajectory of movement", None),
    ("ATTRIBUTE", "Property or quality ascribed to an entity", None),
    ("VALUE", "Quantified measurement or amount", None),
    ("COMPARISON", "Entity being compared against", None),
    ("CONTENT", "Content of communication or thought", None),
    ("MANNER", "Manner or way an action is performed", None),
]

ROOT_ROLE_MAP = {
    "MOTION": "AGENT,THEME,SOURCE,GOAL,LOCATION,TIME,INSTRUMENT,PATH,MANNER",
    "TRANSFER": "AGENT,THEME,SOURCE,GOAL,TIME,INSTRUMENT",
    "COMMUNICATION": "AGENT,PATIENT,CONTENT,THEME,INSTRUMENT,TIME,LOCATION",
    "COGNITION": "AGENT,THEME,TIME,INSTRUMENT",
    "PERCEPTION": "AGENT,THEME,INSTRUMENT,TIME,LOCATION",
    "CREATION": "AGENT,THEME,INSTRUMENT,TIME,LOCATION,SOURCE",
    "DESTRUCTION": "AGENT,THEME,INSTRUMENT,TIME,LOCATION",
    "CHANGE": "AGENT,THEME,SOURCE,GOAL,TIME,LOCATION,INSTRUMENT",
    "POSSESSION": "AGENT,THEME,SOURCE,TIME,LOCATION",
    "INTENTION": "AGENT,THEME,GOAL,TIME",
    "EXISTENCE": "THEME,LOCATION,TIME",
    "EMOTION": "EXPERIENCER,STIMULUS,TIME",
    "DESIRE": "EXPERIENCER,THEME,TIME",
    "PREFERENCE": "EXPERIENCER,THEME,COMPARISON,TIME",
    "JOY": "EXPERIENCER,STIMULUS,TIME",
    "SADNESS": "EXPERIENCER,STIMULUS,TIME",
    "ANGER": "EXPERIENCER,STIMULUS,TIME",
    "FEAR": "EXPERIENCER,STIMULUS,TIME",
    "EVALUATION": "AGENT,THEME,STANDARD,TIME",
    "COMPARISON": "AGENT,THEME,STANDARD,TIME",
    "JUDGMENT": "AGENT,THEME,VERDICT,TIME",
    "APPROVAL": "AGENT,THEME,TIME",
    "CRITICISM": "AGENT,THEME,TIME",
    "SOCIAL": "AGENT,PATIENT,TIME,LOCATION",
    "COOPERATION": "AGENT,PATIENT,THEME,TIME",
    "CONFLICT": "AGENT,PATIENT,THEME,TIME",
    "AGREEMENT": "AGENT,PATIENT,THEME,TIME",
    "PROMISE": "AGENT,THEME,PATIENT,TIME",
    "THREAT": "AGENT,PATIENT,THEME,TIME",
    "REQUEST": "AGENT,THEME,PATIENT,TIME",
    "CAUSATION": "AGENT,THEME,RESULT,TIME",
    "PREVENTION": "AGENT,THEME,TIME",
    "ENABLEMENT": "AGENT,THEME,TIME",
    "ATTEMPT": "AGENT,THEME,TIME",
    "SUCCESS": "AGENT,THEME,TIME",
    "FAILURE": "AGENT,THEME,TIME",
    "ANALYSIS": "AGENT,THEME,TIME,INSTRUMENT",
    "MEMORY": "EXPERIENCER,THEME,TIME",
    "LEARNING": "AGENT,THEME,SOURCE,TIME",
    "TEACHING": "AGENT,THEME,PATIENT,TIME",
    "DECISION": "AGENT,THEME,TIME",
    "BELIEF": "EXPERIENCER,THEME,TIME",
    "STATE": "THEME,LOCATION,TIME",
    "PROPERTY": "THEME,ATTRIBUTE,TIME",
    "QUANTITY": "THEME,VALUE,TIME",
    "TIME_RELATION": "THEME,TIME",
    "LOCATION_STATE": "THEME,LOCATION,TIME",
    "EXPERIENCE": "EXPERIENCER,STIMULUS,TIME",
    "ASSISTANCE": "AGENT,PATIENT,THEME,TIME",
    "TRAVEL": "AGENT,SOURCE,GOAL,PATH,TIME,LOCATION",
    "CAUSE_EFFECT": "AGENT,THEME,RESULT,TIME",
    "ACTION": "AGENT,THEME,TIME,INSTRUMENT,LOCATION",
    "CONSUMPTION": "AGENT,THEME,TIME",
    "REFUSAL": "AGENT,THEME,TIME",
}
